module.exports = {
  "board": [
    [{"toggled":true, "class":"on"},{"toggled":true, "class":"on"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"}],
    [{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"}],
    [{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"}],
    [{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"}],
    [{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"}],
    [{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"}],
    [{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"}],
    [{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"}],
    [{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"}],
    [{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"}]
  ]
};
