module.exports = {
  "board1Start": {
    "pieces":{"1": ["00", "01"], "2": ["91", "92", "93", "94"]},
    "board": [
      [{"toggled":true, "class":"on", "id":"1"},{"toggled":true, "class":"on", "id":"1"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"}],
      [{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"}],
      [{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"}],
      [{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"}],
      [{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"}],
      [{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"}],
      [{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"}],
      [{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"}],
      [{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"}],
      [{"toggled":false, "class":"off"},{"toggled":true, "class":"on", "id":"2"},{"toggled":true, "class":"on", "id":"2"},{"toggled":true, "class":"on", "id":"2"},{"toggled":true, "class":"on", "id":"2"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"}]
    ]
  },
  "board2Start": {
    "pieces":{},
    "board":[
      [{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":true, "class":"on"},{"toggled":true, "class":"on"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"}],
      [{"toggled":true, "class":"on"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"}],
      [{"toggled":true, "class":"on"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"}],
      [{"toggled":true, "class":"on"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"}],
      [{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":true, "class":"on"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"}],
      [{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":true, "class":"on"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"}],
      [{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":true, "class":"on"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"}],
      [{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"}],
      [{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"}],
      [{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"},{"toggled":false, "class":"off"}]
    ]
  }
};
